version: '3'

services:
  database:
    container_name: database
    image: mariadb:11
    environment:
      - MARIADB_ROOT_PASSWORD=${PASSWORD}
      - MARIADB_DATABASE=${DB}
      - MARIADB_USER=${USER}
      - MARIADB_PASSWORD=${PASSWORD}
    restart: on-failure
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - .docker/database:/var/lib/postgresql/data:rw
  app:
    container_name: app
    build: .docker/php
    depends_on:
      - database
      - web
    working_dir: /var/www/html
    tty: true
    ports:
      - "9000:9000"
    links:
      - database
    volumes:
      - /var/www/html/vendor
      - ./:/var/www/html/:cached
    networks:
      - app-network
    environment:
      PHP_IDE_CONFIG: "serverName=symfony-local"
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
  web:
    container_name: web
    build: ./.docker/nginx
    tty: true
    ports:
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - ./:/var/www/html:cached
      - ./.docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  cache:
    container_name: cache
    image: redis:latest
    networks:
      - app-network
networks:
  app-network:
    driver: bridge