version: '3'

services:
  database:
    image: mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=app
      - MARIADB_USER=root
      - MARIADB_PASSWORD=root
    restart: on-failure
    ports:
      - 3306:3306
    volumes:
      - .docker/database:/var/lib/postgresql/data:rw